/// <reference types="tree-sitter-cli/dsl" />
// @ts-check
// https://www.cs.purdue.edu/homes/hosking/m3/reference/syntax.html

module.exports = grammar({
  name: "Modula3",
  // word: ($) =>
  //   choice(
  //     $.AND,
  //     $.ANY,
  //     $.ARRAY,
  //     $.AS,
  //     $.BEGIN,
  //     $.BITS,
  //     $.BRANDED,
  //     $.BY,
  //     $.CASE,
  //     $.CONST,
  //     $.DIV,
  //     $.DO,
  //     $.ELSE,
  //     $.ELSIF,
  //     $.END,
  //     $.EVAL,
  //     $.EXCEPT,
  //     $.EXCEPTION,
  //     $.EXIT,
  //     $.EXPORTS,
  //     $.FINALLY,
  //     $.FOR,
  //     $.FROM,
  //     $.GENERIC,
  //     $.IF,
  //     $.IMPORT,
  //     $.IN,
  //     $.INTERFACE,
  //     $.LOCK,
  //     $.LOOP,
  //     $.METHODS,
  //     $.MOD,
  //     $.MODULE,
  //     $.NOT,
  //     $.OBJECT,
  //     $.OF,
  //     $.OR,
  //     $.OVERRIDES,
  //     $.PROCEDURE,
  //     $.RAISE,
  //     $.RAISES,
  //     $.READONLY,
  //     $.RECORD,
  //     $.REF,
  //     $.REPEAT,
  //     $.RETURN,
  //     $.REVEAL,
  //     $.ROOT,
  //     $.SET,
  //     $.THEN,
  //     $.TO,
  //     $.TRY,
  //     $.TYPE,
  //     $.TYPECASE,
  //     $.UNSAFE,
  //     $.UNTIL,
  //     $.UNTRACED,
  //     $.VALUE,
  //     $.VAR,
  //     $.WHILE,
  //     $.WITH,

  rules: {
    // Compilation unit productions:
    Compilation: ($) =>
      seq(
        optional($.UNSAFE),
        choice(seq(choice($.Interface, $.Module), $.GenInf, $.GenMod)),
      ),
    Interface: ($) =>
      choice(
        seq(
          $.INTERFACE,
          $.Id,
          ";",
          repeat1($.Import),
          repeat1($.Decl),
          $.END,
          $.Id,
          ".",
        ),
        seq($.INTERFACE, $.Id, "=", $.Id, $.GenActls, $.END, $.Id, "."),
      ),
    Module: ($) =>
      choice(
        seq(
          $.MODULE,
          $.Id,
          optional(seq($.EXPORTS, $.IdList)),
          ";",
          repeat1($.Import),
          $.Block,
          $.Id,
          ".",
        ),
        seq(
          $.MODULE,
          $.Id,
          optional(seq($.EXPORTS, $.IdList)),
          "=",
          $.Id,
          $.GenActls,
          $.END,
          $.Id,
          ".",
        ),
      ),
    GenInf: ($) =>
      seq(
        $.GENERIC,
        $.INTERFACE,
        $.Id,
        $.GenFmls,
        ";",
        repeat1($.Import),
        repeat1($.Decl),
        $.END,
        $.Id,
        ".",
      ),
    GenMod: ($) =>
      seq(
        $.GENERIC,
        $.MODULE,
        $.Id,
        $.GenFmls,
        ";",
        optional($.Import),
        $.Block,
        $.Id,
        ".",
      ),
    Import: ($) => choice($.AsImport, $.FromImport),
    AsImport: ($) =>
      seq($.IMPORT, $.ImportItem, repeat1(seq(",", $.ImportItem))),
    FromImport: ($) => seq($.FROM, $.Id, $.IMPORT, $.IdList, ";"),
    Block: ($) => seq(repeat1($.Decl), $.BEGIN, $.S, $.END),
    Decl: ($) =>
      seq(
        choice(
          seq($.CONST, repeat1(seq($.ConstDecl, ";"))),
          seq($.TYPE, repeat1(seq($.TypeDecl, ";"))),
          seq($.EXCEPTION, repeat1(seq($.ExceptionDecl, ";"))),
          seq($.VAR, repeat1(seq($.VariableDecl, ";"))),
          seq($.ProcedureHead, optional(seq("=", $.Block, $.Id)), ";"),
          seq($.REVEAL, repeat1(seq($.QualId, choice("=", "<:"), $.Type, ";"))),
        ),
      ),
    GenFmls: ($) => seq("(", optional($.IdList), ")"),
    GenActls: ($) => seq("(", optional($.IdList), ")"),
    ImportItem: ($) => seq(choice($.Id, $.Id, $.AS, $.Id)),
    ConstDecl: ($) => seq($.Id, optional(seq(":", $.Type)), "=", $.ConstExpr),
    TypeDecl: ($) => seq($.Id, choice("=", "<:"), $.Type),
    ExceptionDecl: ($) => seq($.Id, optional(seq("(", $.Type, ")"))),
    VariableDecl: ($) =>
      seq($.IdList, choice(seq(":", $.Type), seq(":=", $.Expr))),
    ProcedureHead: ($) => seq($.PROCEDURE, $.Id, $.Signature),
    Signature: ($) =>
      seq(
        "(",
        $.Formals,
        ")",
        optional(seq(":", $.Type)),
        optional(seq($.RAISES, $.Raises)),
      ),
    Formals: ($) =>
      optional(seq($.Formal, repeat1(seq(";", $.Formal)), optional(";"))),
    Formal: ($) =>
      seq(
        optional($.Mode),
        $.IdList,
        choice(seq(":", $.Type), seq(":=", $.ConstExpr)),
      ),
    Mode: ($) => choice($.VALUE, $.VAR, $.READONLY),
    Raises: ($) =>
      choice(
        seq("{", optional(seq($.QualId, repeat1(seq(",", $.QualId)))), "}"),
        $.ANY,
      ),
    // Statement productions:
    Stmt: ($) =>
      choice(
        $.AssignSt,
        $.Block,
        $.CallSt,
        $.CaseSt,
        $.ExitSt,
        $.EvalSt,
        $.ForSt,
        $.IfSt,
        $.LockSt,
        $.LoopSt,
        $.RaiseSt,
        $.RepeatSt,
        $.ReturnSt,
        $.TCaseSt,
        $.TryXptSt,
        $.TryFinSt,
        $.WhileSt,
        $.WithSt,
      ),
    S: ($) => optional(seq($.Stmt, repeat1(seq(";", $.Stmt)), optional(";"))),
    AssignSt: ($) => seq($.Expr, ":=", $.Expr),
    CallSt: ($) =>
      seq(
        $.Expr,
        "(",
        optional(seq($.Actual, repeat1(seq(",", $.Actual)))),
        ")",
      ),
    CaseSt: ($) =>
      seq(
        $.CASE,
        $.Expr,
        $.OF,
        optional($.Case),
        repeat1(seq("|", $.Case)),
        optional(seq($.ELSE, $.S)),
        $.END,
      ),
    ExitSt: ($) => $.EXIT,
    EvalSt: ($) => seq($.EVAL, $.Expr),
    ForSt: ($) =>
      seq(
        $.FOR,
        $.Id,
        ":=",
        $.Expr,
        $.TO,
        $.Expr,
        optional(seq($.BY, $.Expr)),
        $.DO,
        $.S,
        $.END,
      ),
    IfSt: ($) =>
      seq(
        $.IF,
        $.Expr,
        $.THEN,
        $.S,
        repeat1(seq($.ELSIF, $.Expr, $.THEN, $.S)),
        optional(seq($.ELSE, $.S)),
        $.END,
      ),
    LockSt: ($) => seq($.LOCK, $.Expr, $.DO, $.S, $.END),
    LoopSt: ($) => seq($.LOOP, $.S, $.END),
    RaiseSt: ($) => seq($.RAISE, $.QualId, optional(seq("(", $.Expr, ")"))),
    RepeatSt: ($) => seq($.REPEAT, $.S, $.UNTIL, $.Expr),
    ReturnSt: ($) => seq($.RETURN, optional($.Expr)),
    TCaseSt: ($) =>
      seq(
        $.TYPECASE,
        $.Expr,
        $.OF,
        optional($.TCase),
        repeat1(seq("|", $.TCase)),
        optional(seq($.ELSE, $.S)),
        $.END,
      ),
    TryXptSt: ($) =>
      seq(
        $.TRY,
        $.S,
        $.EXCEPT,
        optional($.Handler),
        optional(seq("|", $.Handler)),
        optional(seq($.ELSE, $.S)),
        $.END,
      ),
    TryFinSt: ($) => seq($.TRY, $.S, $.FINALLY, $.S, $.END),
    WhileSt: ($) => seq($.WHILE, $.Expr, $.DO, $.S, $.END),
    WithSt: ($) =>
      seq($.WITH, $.Binding, repeat1(seq(",", $.Binding)), $.DO, $.S, $.END),
    Case: ($) => seq($.Labels, repeat1(seq(",", $.Labels)), "=>", $.S),
    Labels: ($) => seq($.ConstExpr, optional(seq("..", $.ConstExpr))),
    Handler: ($) =>
      seq(
        $.QualId,
        repeat1(seq(",", $.QualId)),
        optional(seq("(", $.Id, ")")),
        "=>",
        $.S,
      ),
    TCase: ($) =>
      seq(
        $.Type,
        repeat1(seq(",", $.Type)),
        optional(seq("(", $.Id, ")")),
        "=>",
        $.S,
      ),
    Binding: ($) => seq($.Id, "=", $.Expr),
    Actual: ($) => choice($.Type, seq(optional(seq($.Id, ":=")), $.Expr)),
    // Type productions:
    Type: ($) =>
      choice(
        $.TypeName,
        $.ArrayType,
        $.PackedType,
        $.EnumType,
        $.ObjectType,
        $.ProcedureType,
        $.RecordType,
        $.RefType,
        $.SetType,
        $.SubrangeType,
        seq("(", $.Type, ")"),
      ),
    ArrayType: ($) =>
      seq(
        $.ARRAY,
        optional(seq($.Type, repeat1(seq(",", $.Type)))),
        $.OF,
        $.Type,
      ),
    PackedType: ($) => seq($.BITS, $.ConstExpr, $.FOR, $.Type),
    EnumType: ($) => seq("{", optional($.IdList), "}"),
    ObjectType: ($) =>
      seq(
        optional(choice($.TypeName, $.ObjectType)),
        optional($.Brand),
        $.OBJECT,
        $.Fields,
        optional(seq($.METHODS, $.Methods)),
        optional(seq($.OVERRIDES, $.Overrides)),
        $.END,
      ),
    ProcedureType: ($) => seq($.PROCEDURE, $.Signature),
    RecordType: ($) => seq($.RECORD, $.Fields, $.END),
    RefType: ($) => seq(optional($.UNTRACED), optional($.Brand), $.REF, $.Type),
    SetType: ($) => seq($.SET, $.OF, $.Type),
    SubrangeType: ($) => seq("[", $.ConstExpr, "..", "]"),
    Brand: ($) => seq($.BRANDED, optional($.ConstExpr)),
    Fields: ($) =>
      optional(seq($.Field, repeat1(seq(";", $.Field)), optional(";"))),
    Field: ($) =>
      seq($.IdList, choice(seq(":", $.Type), seq(":=", $.ConstExpr))),
    Methods: ($) =>
      optional(
        seq($.Method, repeat1(optional(seq(";", $.Method))), optional(";")),
      ),
    Method: ($) => seq($.Id, $.Signature, optional(seq(":=", $.ConstExpr))),
    Overrides: ($) =>
      optional(seq($.Override, repeat1(seq(";", $.Override)), optional(";"))),
    Override: ($) => seq($.Id, ":=", $.ConstExpr),

    // Expression productions:
    ConstExpr: ($) => $.Expr,
    Expr: ($) => seq($.E1, repeat1(seq($.OR, $.E1))),
    E1: ($) => seq($.E2, repeat1(seq($.AND, $.E2))),
    E2: ($) => seq(repeat1($.NOT), $.E3),
    E3: ($) => seq($.E4, repeat1(seq($.Relop, $.E4))),
    E4: ($) => seq($.E5, repeat1(seq($.Addop, $.E5))),
    E5: ($) => seq($.E6, repeat1(seq($.Mulop, $.E6))),
    E6: ($) => seq(repeat1(choice("+", "-")), $.E7),
    E7: ($) => seq($.E8, repeat1($.Selector)),
    E8: ($) =>
      choice(
        $.Id,
        $.Number,
        $.CharLiteral,
        $.TextLiteral,
        $.Constructor,
        seq("(", $.Expr, ")"),
      ),

    Relop: ($) => choice("=", "#", "<", "<=", ">", ">=", $.IN),
    Addop: ($) => choice("+", "-", "&"),
    Mulop: ($) => choice("*", "/", $.DIV, $.MOD),

    Selector: ($) =>
      choice(
        "^",
        seq(".", $.Id),
        seq("[", $.Expr, repeat1(seq(",", $.Expr)), "]"),
        seq("(", optional(seq($.Actual, repeat1(seq(",", $.Actual)))), ")"),
      ),
    Constructor: ($) =>
      seq(
        $.Type,
        "{",
        optional(choice($.SetCons, $.RecordCons, $.ArrayCons)),
        "}",
      ),
    SetCons: ($) => seq($.SetElt, repeat1(seq(",", $.SetElt))),
    SetElt: ($) => seq($.Expr, optional(seq("..", $.SetElt))),
    RecordCons: ($) => seq($.RecordElt, repeat1(seq(",", $.RecordElt))),
    RecordElt: ($) => seq(optional(seq($.Id, ":=")), $.Expr),
    ArrayCons: ($) =>
      seq($.Expr, repeat1(seq(",", $.Expr)), optional(seq(",", ":"))),

    // Miscellaneous productions:
    IdList: ($) => seq($.Id, repeat1(seq(",", $.Id))),
    QualId: ($) => seq($.Id, optional(seq(",", $.Id))),
    TypeName: ($) => choice($.QualId, $.ROOT, seq($.UNTRACED, $.ROOT)),

    // Token productions:
    Id: ($) => seq($.Letter, repeat1(choice($.Letter, $.Digit, "_"))),
    Literal: ($) => choice($.Number, $.CharLiteral, $.TextLiteral),
    CharLiteral: ($) =>
      seq("'", choice($.PrintingChar, $.Escape, $.DQUOTE), "'"),
    TextLiteral: ($) =>
      seq($.DQUOTE, repeat(choice($.PrintingChar, $.Escape, "'")), $.DQUOTE),
    DQUOTE: () => '"',
    Digit: () => /[0-9]/,
    HexDigit: ($) => choice($.Digit, /[a-fA-F]/),
    Letter: () => /[a-zA-Z]/,
    OctalDigit: () => /[0-7]/,
    OtherChar: () =>
      choice(
        " ",
        "!",
        "#",
        "$",
        "%",
        "&",
        "(",
        ")",
        "*",
        "+",
        ",",
        "-",
        ".",
        "/",
        ":",
        ";",
        "<",
        "=",
        ">",
        "?",
        "@",
        "[",
        "]",
        "^",
        "_",
        "`",
        "{",
        "}",
        " ",
      ),
    PrintingChar: ($) => choice($.Letter, $.Digit),
    Exp: ($) =>
      seq(
        choice("E", "e", "D", "d", "X", "x"),
        optional(choice("+", "-")),
        repeat1($.Digit),
      ),
    Escape: ($) =>
      choice(
        seq("\\", "n"),
        seq("\\", "t"),
        seq("\\", "r"),
        seq("\\", "f"),
        seq("\\", "\\"),
        seq("\\", "\\"),
        seq("\\", $.DQUOTE),
        seq("\\", $.OctalDigit, $.OctalDigit, $.OctalDigit),
      ),
    Number: ($) =>
      choice(
        repeat1($.Digit),
        seq(repeat1($.Digit), "_", $.HexDigit, repeat($.HexDigit)),
        seq(repeat1($.Digit), ".", repeat1($.Digit), optional($.Exp)),
      ),
    // Keywords:
    AND: ($) => "AND",
    ANY: ($) => "ANY",
    ARRAY: ($) => "ARRAY",
    AS: ($) => "AS",
    BEGIN: ($) => "BEGIN",
    BITS: ($) => "BITS",
    BRANDED: ($) => "BRANDED",
    BY: ($) => "BY",
    CASE: ($) => "CASE",
    CONST: ($) => "CONST",
    DIV: ($) => "DIV",
    DO: ($) => "DO",
    ELSE: ($) => "ELSE",
    ELSIF: ($) => "ELSIF",
    END: ($) => "END",
    EVAL: ($) => "EVAL",
    EXCEPT: ($) => "EXCEPT",
    EXCEPTION: ($) => "EXCEPTION",
    EXIT: ($) => "EXIT",
    EXPORTS: ($) => "EXPORTS",
    FINALLY: ($) => "FINALLY",
    FOR: ($) => "FOR",
    FROM: ($) => "FROM",
    GENERIC: ($) => "GENERIC",
    IF: ($) => "IF",
    IMPORT: ($) => "IMPORT",
    IN: ($) => "IN",
    INTERFACE: ($) => "INTERFACE",
    LOCK: ($) => "LOCK",
    LOOP: ($) => "LOOP",
    METHODS: ($) => "METHODS",
    MOD: ($) => "MOD",
    MODULE: ($) => "MODULE",
    NOT: ($) => "KNOT",
    OBJECT: ($) => "OBJECT",
    OF: ($) => "OF",
    OR: ($) => "OR",
    OVERRIDES: ($) => "OVERRIDES",
    PROCEDURE: ($) => "PROCEDURE",
    RAISE: ($) => "RAISE",
    RAISES: ($) => "RAISES",
    READONLY: ($) => "READONLY",
    RECORD: ($) => "RECORD",
    REF: ($) => "REF",
    REPEAT: ($) => "REPEAT",
    RETURN: ($) => "RETURN",
    REVEAL: ($) => "REVEAL",
    ROOT: ($) => "ROOT",
    SET: ($) => "SET",
    THEN: ($) => "THEN",
    TO: ($) => "TO",
    TRY: ($) => "TRY",
    TYPE: ($) => "TYPE",
    TYPECASE: ($) => "TYPECASE",
    UNSAFE: ($) => "UNSAFE",
    UNTIL: ($) => "UNTIL",
    UNTRACED: ($) => "UNTRACED",
    VALUE: ($) => "VALUE",
    VAR: ($) => "VAR",
    WHILE: ($) => "WHILE",
    WITH: ($) => "WITH",

    // Reserved Identifiers:
    ABS: ($) => "ABS",
    ADDRESS: ($) => "ADDRESS",
    ADR: ($) => "ADR",
    ADRSIZE: ($) => "ADRSIZE",
    BITSIZE: ($) => "BITSIZE",
    BOOLEAN: ($) => "BOOLEAN",
    BYTESIZE: ($) => "BYTESIZE",
    CARDINAL: ($) => "CARDINAL",
    CEILING: ($) => "CEILING",
    CHAR: ($) => "CHAR",
    DEC: ($) => "DEC",
    DISPOSE: ($) => "DISPOSE",
    EXTENDED: ($) => "EXTENDED",
    FALSE: ($) => "FALSE",
    FIRST: ($) => "FIRST",
    FLOAT: ($) => "FLOAT",
    FLOOR: ($) => "FLOOR",
    INC: ($) => "INC",
    INTEGER: ($) => "INTEGER",
    ISTYPE: ($) => "ISTYPE",
    LAST: ($) => "LAST",
    LONGINT: ($) => "LONGINT",
    LONGREAL: ($) => "LONGREAL",
    LOOPHOLE: ($) => "LOOPHOLE",
    MAX: ($) => "MAX",
    MIN: ($) => "MIN",
    MUTEX: ($) => "MUTEX",
    NARROW: ($) => "NARROW",
    NEW: ($) => "NEW",
    NIL: ($) => "NIL",
    NULL: ($) => "NULL",
    NUMBER: ($) => "NUMBER",
    ORD: ($) => "ORD",
    REAL: ($) => "REAL",
    REFANY: ($) => "REFANY",
    ROUND: ($) => "ROUND",
    SUBARRAY: ($) => "SUBARRAY",
    TEXT: ($) => "TEXT",
    TRUE: ($) => "TRUE",
    TRUNC: ($) => "TRUNC",
    TYPECODE: ($) => "TYPECODE",
    VAL: ($) => "VAL",
  },
});
